### ISSUE TITLE
Cannot save changes of commandLineTools from the "visual" mode

### ISSUE THREAD

**Issue by KerstenBreuer** [rabix/composer#328] opened 2018-01-08 14:16 UTC
When I open and edit an output id of a cwl CommandLineTool in the "visual" mode, the changes don't show up in the "code" view mode and cannot be saved. The opposite way works (when I edit in "code" mode the changes are updated to the "visual" mode).

The bug only occurs if I open an existing cwl file. If I create a new one, everything is fine. Moreover, as far as I experienced, the bug is restricted to the "ID" field in the "OUTPUT PORTS" category.

**Comment by ivanbatic** [comment] 2018-02-07 14:30
Duplicate of https://github.com/rabix/composer/issues/326

**Closed by ivanbatic** 2018-02-07 14:30 UTC
